version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: cafeteria_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: ${APP_ENV}
    depends_on:
      - db
    command: >
      sh -c "
      if [ '$APP_ENV' = 'development' ]; then
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload;
      else
        uvicorn main:app --host 0.0.0.0 --port 8000;
      fi"

  db:
    image: postgres:15
    container_name: cafeteria_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: